#!/bin/ksh

USAGE="$0 [-r][-v]"

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

while getopts "rv" opt
do
	case "$opt" in
		r)	RESUME=true;;
		v)	VERBOSE=true;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

case "${GPG_TTY}" in
	/dev/[pt]ty*)	;; # ok
	*)	echo "Uh-oh, that will never work. GPG_TTY ${GPG_TTY} is not a valid TTY"
		exit 1;;
esac

echo "Are you sure??"; read ans junk
case $ans in y*);; *) echo "OK I wont"; exit 1;; esac

set -x

if [ true != "${RESUME}" ]; then
	mvn release:clean release:prepare
fi

mvn -Prelease -DskipTests -Dmaven.test.skip release:perform
