= DarwinSys-API
Ian Darwin <https://github.com/IanDarwin[@IanDarwin]>
// settings:
:page-layout: base
:source-language: java
:language: {source-language}

This is a collection of Java classes that I've found useful,
classes which implement some useful operations that one would normally
have to re-implement many times over.
In most cases "found useful" means used more than once, but not always. 

See the http://javacook.darwinsys.com/[Author's Book Site] and the
http://java.oreilly.com/catalog/javacook/[O'Reilly Site]
for more information on the book which accompanies this source code.

The codebase has been together for years,
and has somewhat grown like topsy, so lopsy may be lopping
off some of its leaves as time goes by. He will try to avoid
breaking any of the projects that uses it; if he does so, please
get in touch in the usual way(s).

As of 1.1.0, Java 8 (JDK 1.8) is now the minimum to build and use this API.
For Java 6 or 7 you have to stick to version 1.0.5.

.*Build*
image:http://img.shields.io/badge/license-BSD2-green.svg[link="http://github.com/IanDarwin/darwinsys-api"]
image:https://maven-badges.herokuapp.com/maven-central/com.darwinsys/darwinsys-api/badge.svg[
	link="https://maven-badges.herokuapp.com/maven-central/com.darwinsys/darwinsys-api"]

== Testing

N.B. You MUST install a minimal $HOME/.db.properties to run the tests under Maven.  
This needs to be automated, but for now, there it is. Rather, here it is:

----
# This totally fake .db.properties should be copied to your home directory.
# Values here are just for running the JUnit tests on the ConnectionUtils
test.DBDriver=com.darwinsys.sql.MockJDBCDriver
test.DBURL=jdbc:mock:you_make_me_laugh
test.DBUser=testName
test.DBPassword=testPassword
----

Cheers

Ian Darwin

