= DarwinSys-API
Ian Darwin <https://github.com/IanDarwin[@IanDarwin]>
// settings:
:page-layout: base
:source-language: java
:language: {source-language}

This is a collection of Java classes that I've found useful,
classes which implement some useful operations that one would normally
have to re-implement many times over.
In most cases "found useful" means used more than once, but not always. 

Notes: 
* In late 2019, the 'testng' package graduated to its own project,
darwinsys-testing, to aid in modularizing this (there being no module
support for JUnit 4 three years after Jigsaw was announced), and anyway,
a general-purpose library probably has no business dragging in a dependency
on a testing library.
* In 2017 the servlet and JSP packages graduated from
darwinsys-api to darwinsys-ee; which you now may need!

See the http://javacook.darwinsys.com/[Author's Book Site] and the
http://java.oreilly.com/catalog/javacook/[O'Reilly Site]
for more information on the book which accompanies this source code.

The codebase has been together for years,
and has somewhat grown like topsy, so lopsy may be lopping
off some of its leaves as time goes by. He will try to avoid
breaking any of the projects that uses it; if he does so, please
get in touch in the usual way(s).

Java 16 (JDK 1.16) is now the minimum to build and use this API.
For older releases, either say on 1.5.x, or just upgrade your JDK.

.*Build*
image:http://img.shields.io/badge/license-BSD2-green.svg[link="http://github.com/IanDarwin/darwinsys-api"]
image:https://maven-badges.herokuapp.com/maven-central/com.darwinsys/darwinsys-api/badge.svg[
	link="https://maven-badges.herokuapp.com/maven-central/com.darwinsys/darwinsys-api"]

== Testing

N.B. You MUST have a minimal $HOME/.db.properties to run the tests under Maven.  
This needs to be automated, but for now, there it is. Rather, here it is.
Create the file, or, if you have the file, add these entries once.

----
# This totally fake .db.properties should be copied to your home directory.
# Values here are just for running the JUnit tests on the ConnectionUtils
test.DBDriver=com.darwinsys.sql.MockJDBCDriver
test.DBURL=jdbc:mock:it_is_a_mock_after_all
test.DBUser=testName
test.DBPassword=testPassword
----

== TODO

CalendarEvent:

* get tests working
* finish two newCalendarEvent methods

JPMS

Cheers

Ian Darwin

