#!/bin/sh

set -x

(
cd build

sed 's/^Installer-class.*/Installer-class: gui.JFrameDemo/' com/darwinsys/installers/MANIFEST.stub > /tmp/MANIFEST.stub
mkdir gui; copy $js/build/gui/JFrameDemo* gui
jar cfvm ../installer.jar /tmp/MANIFEST.stub \
	com/darwinsys/installers/*.class \
	com/darwinsys/swingui/UtilGUI.class \
	gui/*.class
)

java -jar installer.jar
