package com.darwinsys.util;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	ArrayIteratorTest.class,
	FilePropertiesTest.class,
	FixedLengthFIFOTest.class,
	IndexListTest.class,
	MiniMaxTest.class,
	OrdinalFormatTest.class,
	PhoneNumberUtilTest.class,
	RecentItemstest.class,
	ScaledNumberFormatFormatOldTest.class,
	ScaledNumberFormatFormatTest.class,
	ScaledNumberFormatFormatZZTest.class,
	ScaledNumberFormatParseTest.class,
	VariableMapTest.class,
})
public class AllTests {
	// No Code Needed
}

