package com.darwinsys.io;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	ClassSourceUtilsTest.class,
	CrawlerTest.class,
	FileIOTest.class,
	FileSaverTest.class,
	TextAreaOutputStreamTest.class,
	TextAreaWriterTest.class
})
public class AllTests {
	// No Code Needed
}

