package com.darwinsys.sql;


/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	ConfigurationTest.class,
	ConnectionUtilTest.class,
	ReaderParserTest.class
	//ResultsDecoratorTextTest.class
})
public class AllTests {
	// No Code Needed
}

