#!/bin/sh

# Start a clipper written in Java for copy/paste shortcuts

JDK_VER=21
DOS_VER=1.9.0-SNAPSHOT

JAVA_HOME=${JAVA_HOME-/usr/local/jdk-${JDK_VER}}

DARWINSYS_JAR=${HOME}/.m2/repository/com/darwinsys/darwinsys-api/${DOS_VER}/darwinsys-api-${DOS_VER}.jar

${JAVA_HOME}/bin/java -classpath ${DARWINSYS_JAR} com.darwinsys.jclipboard.JClipBoard &
