package com.darwinsys.lang;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	GetOptConstructorTest.class,
	GetOptDescTest.class,
	GetOptTestNewPattern.class,
	GetOptTestOldPattern.class,
	MutableIntegerTest.class,
	StringFormatTest.class,
	StringUtilTest.class
})
public class AllTests {
	// No Code Needed
}

